### ISSUE TITLE
connectionTimeout units

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-sdk-spec#13]
Is `connectionTimeout` in the [config](https://github.com/stormpath/stormpath-sdk-spec/blob/master/specifications/config.md) in seconds, or milliseconds?

In the JSDK, for example, the timeout is specified in milliseconds: https://github.com/stormpath/stormpath-sdk-java/blob/master/api/src/main/java/com/stormpath/sdk/client/ClientBuilder.java#L333

**Comment by robertjd** [comment]
Honestly I prefer seconds for these kinds of values, as they are simpler to reason with.  Is there any reason why a timeout would need a sub-second value?

**Comment by nbarbettini** [comment]
No reason that I can think of.

**Comment by lhazlewood** [comment]
It is milliseconds in the Java SDK because this is the idiomatic unit of time in Java when no time unit is specified.

**Comment by nbarbettini** [comment]
I'm guessing doing the idiomatic thing is the case across all of our implementations. It's probably not crucial to update this spec to standardize it, just slightly confusing when referring back to this.
