### ISSUE TITLE
The documentation is incomplete.

### ISSUE THREAD

**Issue by appodeepa** [stormpath/stormpath-sdk-spec#8]
Take this page for example: https://github.com/stormpath/stormpath-sdk-spec/blob/master/specifications/account.md which is the best I can find when looking for express options.

How are we to build on Stormpath when the full documentation isn't available?

**Comment by rdegges** [comment]
This isn't a complete spec just yet -- it's something we've been working on, but is in no way completed. We're still in the process of writing this all up so we can standardize our integrations between languages.

The most accurate, and up-to-date information can be found on our website, here: http://docs.stormpath.com/rest/product-guide/

**Comment by appodeepa** [comment]
I ended up using this tutorial: https://stormpath.com/blog/build-nodejs-express-stormpath-app/ - which worked a charm, yet wasted way too many hours yesterday trying to find key bits of info which flies in the face of Stormpath being a time and frustration saver. 

Overall a great service. Put together a pack of cohesive docs (and fix the dead links on your blog) and it will be even better.

**Comment by rdegges** [comment]
Thank you for the feedback -- this is really useful.

I promise we'll be improving this very soon. We've been working really hard to totally re-do our docs, and are getting pretty close to launching those =) This will hopefully solve a lot of frustration in the future! <3
